# DataSource Config
spring:
  datasource:
    schema: classpath:sql/costume.sql
    url: jdbc:mysql://39.97.242.132:3306/costume?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 19970701Xzj.
  thymeleaf:
    check-template-location: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl