# DataSource Config
spring:
  datasource:
    schema: classpath:sql/costume.sql
    url: jdbc:mysql://localhost/costume?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 19970701
  thymeleaf:
    check-template-location: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file: log/myLog.log